lib/Db/RecipeDb.php
I added some modifications to have a very simple fuzzy search functionality based on recipe name, keeping the keyword search in place
=> Added code for fuzzy searching

lib/Service/RecipeService.php
This updates the `file_get_contents` to use a User Agent in its requests.
=> #24 Adds User Agent

draft-release.sh
=> Avoid error message on next release

templates/content/recipe.php
=> Removed duplicate text servings

translationfiles/fr/cookbook.po
Here is the French translation
Regards
=> French translation

translationfiles/README.md, translationfiles/README_TRANSLATIONS.md
I added a few lines of documentation how to generate translations. Please review them according to your preferences how translations should be made.
=> Added documentation for translators

draft-release.sh
=> Added internationalization code in release script

translationfiles/README.md, translationfiles/de/cookbook.po, translationfiles/de_DE/cookbook.po, translationfiles/es/cookbook.po, translationfiles/fr/cookbook.po, translationfiles/pl/cookbook.po, translationfiles/templates/cookbook.pot, update-pot.sh
This PR should allow to update the translation related files as code grows.
This problem is also referenced in some:tm: issue here. There was a missing part in the translation template file.
=> Allow update of translations

translationfiles/de/cookbook.po, translationfiles/de_DE/cookbook.po, translationfiles/es/cookbook.po, translationfiles/fr/cookbook.po, translationfiles/pl/cookbook.po, translationfiles/templates/cookbook.pot
Recent code updated cause the tranlsations to be outdated. This brings the translation files to the current state of the code to help translations by others.
=> Update the translation files

translationfiles/README.md, translationfiles/nl/cookbook.po
Small question: is there really an important difference between "Prep time" and "Preparation time"? Does it need to be shorter? Because I translated them the same... (Idem for "Cook time" vs "Cooking time")
=> Add dutch translations

lib/Controller/PageController.php, lib/Controller/RecipeController.php, lib/Service/RecipeService.php
=> Use dependency injection to get rid of the RecipeService Constructor

tests/Integration/AppTest.php, tests/Unit/Controller/PageControllerTest.php, tests/bootstrap.php
There are only the very rudimentary tests that @mrzapp  has written available, but these should run now by simply running `phpunit` and `phpunit -x phpunit.integration.xml` inside the root folder for the app. I want to get this out asap so we can all start writing tests.
=> Basic testing setup for unit and integration tests

lib/Service/RecipeService.php, templates/content/edit.php, templates/content/recipe.php
=> Parse totalTime as input field

lib/Service/RecipeService.php
I would start to break the service up into smaller services where applicable.
=> First round of refactoring for the recipeService

lib/Controller/PageController.php, templates/index.php
Before I continue cleaning up, I want to get this out of the way.
=> App name from AppName Variable and some deleted templates that are not used

lib/Service/RecipeService.php, tests/Unit/Service/ValidateDurationTest.php
I slimmed down the validateDuration method, so it only does one job. I also added some tests that should definitely be expanded by somebody who knows about DateIntervals. I suggest @Timvde
=> Streamline validateDuration method and add some tests

.gitignore, lib/Service/RecipeService.php
Fixes Issue #96 
Added a simple Regex before the filter to select the first uninterrupted sequence of numbers as the correct number in the string.
=> Feature/incorrect servings#96

lib/Controller/RecipeController.php, lib/Db/RecipeDb.php, lib/Service/RecipeService.php, templates/navigation/index.php
All Recipes without a single keyword are grouped under the "Uncategorized" word, as requested in #110.
The category is currently called "Uncategorized". Many Dictionaries seem to have a problem with this word although i could not find a clear indication that it does not exists / is not correct. Maybe we could think of changing it to something different?
I could add German Translation here as well.
=> Added "Uncategorized" Category

templates/content/edit.php, templates/content/recipe.php
Adds the tool keyword to recipes as mentioned in #85 
The "tool" is already properly parsed if it is present in the json.
The Translation is no yet provided. I could add German Translation if someone tells me if i should use the `de` or the `de_DE` translation file.
=> Added Tool to Edit and View

translationfiles/fr/cookbook.po
Here a update for french translation
=> Update french translation

translationfiles/ru/cookbook.po
I have translated the strings to Russian language
=> Russian translation

lib/Service/RecipeService.php
this will use the content attribute as suggested
=> fix #196 - use content attribute if it exists for ingredient element

css/style.css, js/script.js, lib/Controller/ConfigController.php, lib/Controller/MainController.php, lib/Service/RecipeService.php, templates/content/recipe.php, templates/settings/index.php
Fixes #161.
Adds a checkbox in the settings to choose if the image should be printed with the recipe. The image is printed as is (see #176).
=> Implement setting to print image

src/components/AppNavi.vue
Resolves #183
Please note that this still does not check if the actual PHP script that imports the recipe completed successfully or not.
=> Clear URL after successful recipe import

README.md
the link to the parser points to the develop branch which doesn't exist, I pointed it to master
=> fix broken link to parser

src/components/AppControls.vue, src/components/AppNavi.vue
=> Improved tooltips for some controls

CHANGELOG.md, appinfo/routes.php
Remove issue in current PRs due to updated dependency
=> Update files according to most recent version of php-cs-fixer

CHANGELOG.md, lib/Service/RecipeService.php, src/components/EditMultiselectInputGroup.vue, src/components/RecipeEdit.vue, src/components/RecipeNutritionInfoItem.vue, src/components/RecipeView.vue
Made nutrition information visible in the UI.
To test viewing the information, you can import some recipe, e.g., <https://www.taste.com.au/recipes/seared-kangaroo-raspberry-glaze/8179a9df-2188-4050-adea-2163424650ed?r=recipes/nutritioninformation>
I also added an editing component for nutrition information. 
@sam-19: It would be great, if you could review this PR!
Closes #185, closes #225 
**Viewing nutrition information**
**Editing nutrition information**
=> Show nutritional infos of recipe and make them editable

CHANGELOG.md, src/components/RecipeEdit.vue
=> Fix cooking time not being saved

.github/workflows/deploy-test.yml, CHANGELOG.md
This should make CI work with the correct application keys
=> Switch to correct private key secret

CHANGELOG.md, lib/Db/RecipeDb.php
=> Fixed keywords being returned multiple times for recipes

CHANGELOG.md, lib/Db/RecipeDb.php, lib/Service/DbCacheService.php
=> Handle recipes without category well

CHANGELOG.md, src/components/EditImageField.vue
=> Propagate changes of the image to the recipe

CHANGELOG.md, src/components/EditInputGroup.vue
=> Allow pasting of normal content

CHANGELOG.md, src/components/AppIndex.vue
=> Speedup keyword calculation using computed properties

CHANGELOG.md, src/components/AppControls.vue, src/components/AppIndex.vue, src/components/AppMain.vue, src/components/AppNavi.vue, src/components/RecipeEdit.vue, src/store/index.js
Centralized some recipe server call functionality as Vuex actions so they can be easily changed and reused.
- create recipe
- update recipe
- delete recipe
- updating the recipe directory path
Closes #542
=> Added Vuex action for updating recipe directory

CHANGELOG.md, src/components/AppNavi.vue
=> Added recipe icon in navigation pane 

.github/actions/run-tests/run-locally.sh, .github/workflows/build-test-images.yml, CHANGELOG.md
The CI docker images are missing the corrects tags
=> Build all images for docker hub correctly

CHANGELOG.md, src/components/RecipeView.vue
=> Corrected regular expression to work with safari

CHANGELOG.md, src/components/EditMultiselectInputGroup.vue, src/components/RecipeEdit.vue
=> Added translatable placeholder for nutritient selection

lib/Db/DbTypesPolyfillHelper.php, lib/Db/RecipeDb.php
Create a class that allows installing in NC 21 by introducing a helper class to cope with incompatibilities.
=> Polyfill DB types for NC 21

.github/workflows/tests.yml, CHANGELOG.md, appinfo/info.xml
=> Support only current NC core versions

.github/actions/deploy/appinfo/info.xml.dist, CHANGELOG.md, appinfo/info.xml
Corrected bug in deploy script
=> Drop support for old NC versions

CHANGELOG.md, lib/Controller/RecipeController.php, lib/Service/RecipeService.php, src/components/RecipeCard.vue, src/components/RecipeList.vue
=> Allow ordering recipe list

CHANGELOG.md, src/components/EditInputField.vue
=> Open recipe-ref popup only on hash input

CHANGELOG.md, src/components/AppSettings.vue, src/components/EditMultiselectInputGroup.vue, src/components/RecipeEdit.vue, src/store/index.js
=> Fix reindexing and editing nutrition information

CHANGELOG.md, lib/Migration/Version000000Date20210427082010.php
=> Added migration to add indices to all tables

CHANGELOG.md, src/components/AppSettings.vue, src/components/RecipeList.vue, src/components/RecipeListKeywordCloud.vue, src/main.js, src/store/index.js
=> Enhanced tag cloud

CHANGELOG.md, src/components/AppControls.vue, src/components/AppNavi.vue
=> Corrected responsive styles around 1024 by reducing complexity

.github/actions/run-tests/docker-compose.yml, .github/actions/run-tests/run-locally.sh, .github/actions/run-tests/scripts/set_custom_apps_path.php, .github/actions/run-tests/tests/Dockerfile, .github/actions/run-tests/tests/entrypoints/default-entrypoint.sh, .github/actions/run-tests/tests/entrypoints/minimal-default-entrypoint.sh, .github/actions/run-tests/tests/entrypoints/test.sh, .github/actions/run-tests/tests/xdebug.config, CHANGELOG.md
This should fix a breaking change in #780 most probably.
=> Reenable step debugging during automated testing

CHANGELOG.md, README.md
=> Adding Nook to README

CHANGELOG.md, lib/Service/DbCacheService.php, lib/Service/RecipeService.php
=> Smoothly handle arrays of keywords in the JSON file

.github/actions/deploy/appinfo/info.xml.dist, .github/workflows/tests.yml, CHANGELOG.md
=> Update compatible versions of NC

CHANGELOG.md, package.json, src/guest.js, src/main.js
See https://docs.nextcloud.com/server/stable/developer_manual/app_publishing_maintenance/upgrade-guide.html#id7
=> Removed deprecated global variable OC.generateUrl

CHANGELOG.md, src/components/EditInputGroup.vue
=> Allow for newlines in multiline text to be inserted with shift+enter

.github/workflows/deploy-appstore.yml, .github/workflows/tests.yml, CHANGELOG.md
This should speed up some NPM actions as less network interaction is needed.
=> Use NPM folders from internal cache

.github/actions/deploy/appinfo/info.xml.dist, .github/workflows/tests.yml, CHANGELOG.md, appinfo/info.xml
=> Compatibility with NC24

CHANGELOG.md, src/components/AppMain.vue
=> Fix regression during scrolling in edit mode

.github/workflows/pull-checks.yml, CHANGELOG.md
After the fixup bot was deprecated, adding the action in order to reenable it.
=> Readded diabled checks

CHANGELOG.md, lib/Helper/HtmlToDomParser.php, tests/Unit/Helper/HtmlToDomParserTest.php
Closes #1022.
@Valdnet is this correctly done as you suggested? Please approve if yes.
=> Use singular/plural form for translations

CHANGELOG.md, package-lock.json, package.json
=> Migration of Sass to dart sass

lib/Service/DbCacheService.php
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
=> l10n: Change to uppercase

.github/actions/deploy/appinfo/info.xml.dist, CHANGELOG.md, appinfo/info.xml
To make the PHP version check compatible with #1093
=> Fix minimal PHP version

.eslintrc.yml, CHANGELOG.md, package-lock.json, package.json, src/components/AppControls.vue, webpack.config.js
=> Use of material printer icon

CHANGELOG.md, src/components/RecipeView.vue
This is a first approach to solve #1078
=> Changed ordering on mobile devices and printouts

src/components/RecipeEdit.vue
Reported at Transifex.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>
=> l10n: Fixed grammar

.github/actions/run-tests/config/apache/httpd.conf, .github/actions/run-tests/config/nginx/conf.d/default.conf, .github/actions/run-tests/docker-compose.yml, .github/actions/run-tests/extract-annotations.py, .github/actions/run-tests/reset-from-container.sh, .github/actions/run-tests/run-locally.sh, .github/actions/run-tests/run-occ.sh, .github/actions/run-tests/scripts/enable_app_install_script.php, .github/actions/run-tests/scripts/set_custom_apps_path.php, .github/actions/run-tests/scripts/set_debug_mode.php, .github/actions/run-tests/tests/Dockerfile, .vscode/launch.json, CHANGELOG.md
This fixes a regression in #1137 related to the debugging framework.
=> Corrected the paths of the automated tests

CHANGELOG.md, lib/Controller/RecipeController.php, lib/Helper/Filter/Output/EnsureNutritionPresentFilter.php, lib/Helper/Filter/RecipeJSONOutputFilter.php, src/components/RecipeView.vue, tests/Unit/Controller/RecipeControllerTest.php, tests/Unit/Helper/Filter/Output/EnsureNutritionPresentFilterTest.php, tests/Unit/Helper/Filter/RecipeJSONOutputFilterTest.php
=> Make the nutrition object be a JSON object always

CHANGELOG.md, package-lock.json, package.json, src/components/AppControls/AppControls.vue, src/components/AppNavi.vue, src/components/EditInputField.vue, src/components/RecipeIngredient.vue, src/components/RecipeInstruction.vue, src/components/RecipeTool.vue, src/components/RecipeView.vue
This is a major update of `sass-loader` and thus needed to be done manually.
=> Update @nextcloud/webpack-vue-config and sass-loader

CHANGELOG.md, docs/dev/api/0.1.0/index.html, docs/dev/api/0.1.0/internal-cookbook.yaml, docs/dev/api/0.1.0/internal.html, docs/dev/api/0.1.0/objects.yaml, docs/dev/api/0.1.0/openapi-cookbook.yaml, docs/dev/api/changelog/0.md, docs/dev/api/index.md, docs/dev/deployment.md
This is a quick description of all changes to be carried out for the public API related to the fixture of #1179.
=> Write documentation on new API endpoints

CHANGELOG.md, lib/Helper/Filter/JSON/ExtractImageUrlFilter.php, lib/Helper/Filter/JSON/FixDescriptionFilter.php, lib/Helper/Filter/JSON/FixDurationsFilter.php, lib/Helper/Filter/JSON/FixIngredientsFilter.php, lib/Helper/Filter/JSON/FixInstructionsFilter.php, lib/Helper/Filter/JSON/FixKeywordsFilter.php, lib/Helper/Filter/JSON/FixNutritionFilter.php, lib/Helper/Filter/JSON/FixRecipeYieldFilter.php, lib/Helper/Filter/JSON/FixToolsFilter.php, lib/Helper/Filter/JSON/FixUrlFilter.php, lib/Helper/Filter/Output/EnsureNutritionPresentFilter.php, lib/Helper/HtmlToDomParser.php, lib/Service/HtmlDownloadService.php, tests/Integration/Helper/Filter/JSON/FixIngredientsFilterTest.php, tests/Integration/Helper/Filter/JSON/FixInstructionsFilterTest.php, tests/Integration/Helper/Filter/JSON/FixToolsFilterTest.php, tests/Unit/Helper/Filter/JSON/ExtractImageUrlFilterTest.php, tests/Unit/Helper/Filter/JSON/FixDescriptionFilterTest.php, tests/Unit/Helper/Filter/JSON/FixDurationsFilterTest.php, tests/Unit/Helper/Filter/JSON/FixIngredientsFilterTest.php, tests/Unit/Helper/Filter/JSON/FixInstructionsFilterTest.php, tests/Unit/Helper/Filter/JSON/FixKeywordsFilterTest.php, tests/Unit/Helper/Filter/JSON/FixNutritionFilterTest.php, tests/Unit/Helper/Filter/JSON/FixRecipeYieldFilterTest.php, tests/Unit/Helper/Filter/JSON/FixToolsFilterTest.php, tests/Unit/Helper/Filter/JSON/FixUrlFilterTest.php, tests/Unit/Helper/Filter/Output/EnsureNutritionPresentFilterTest.php, tests/Unit/Helper/HtmlToDomParserTest.php, tests/Unit/Service/HtmlDownloadServiceTest.php
=> Migrate ILogger to LoggerInterface

CHANGELOG.md, templates/invalid_guest.php
=> Update the template for public pages

CHANGELOG.md, README.md
Signed-off-by: TheMBeat <thembeat@gmx.de>
Added a new client and badges to the readme
=> Added a new client and badges to the readme

CHANGELOG.md, lib/Service/RecipeService.php
=> Quick fix to store imported HTML file as a backup for future use

CHANGELOG.md, lib/Helper/HTMLParser/HttpJsonLdParser.php, lib/Service/JsonService.php, tests/Unit/Helper/HTMLParser/HttpJsonLdParserTest.php, tests/Unit/Helper/HTMLParser/res_JsonLd/caseJ.html, tests/Unit/Helper/HTMLParser/res_JsonLd/caseJ.json, tests/Unit/Helper/HTMLParser/res_JsonLd/caseJ.src, tests/Unit/Service/JsonServiceTest.php
=> Make parser more generic to handle more websites

package-lock.json
Update some packages to remove critical security issue
=> Update some NPM packages

CHANGELOG.md, src/components/AppControls/AppControls.vue
=> Add translation for "None" (no category selected)

package-lock.json
Signed-off-by: Christian Wolf <github@christianwolf.email>
=> Update loader-utils to 1.4.2

.github/workflows/pull-checks.yml
This should simplify automatically merging of dependabot PRs
=> Update workflows to handle pull requests correctly

.github/workflows/pull-checks.yml
Backport of #1398
Correction of #1399
=> Backport of fixture of workflows

.eslintrc.yml, .vscode/launch.json, .vscode/settings.json, CHANGELOG.md, DEVELOPMENT.md, cookbook.code-workspace, docs/dev/contributing/code_coverage.md, docs/dev/contributing/index.md, docs/dev/contributing/setup.md, webpack.config.js
=> Backport of Update docker development environment

CHANGELOG.md, docs/dev/api/0.1.1/objects.yaml, docs/dev/api/index.md
This fixes some issues in the OpenAPI specifications after rework of it.
=> Fix bugs in openapi 0.1.1

CHANGELOG.md, src/components/RecipeView.vue
This pull requests adds a copy to clipboard action to the RecipeView as described in #1601 
See it in action here:
=> Add copy to clipboard action for ingredients

CHANGELOG.md, src/components/EditTimeField.vue
=> Fix width of timer input fields

.github/workflows/tests.yml
Currently, some test fail causing trouble with PRs. This should fix the appropriate action scripts.
None
=> Fix the path after installing xq using pip

.github/actions/run-tests/requirements.txt, .github/actions/run-tests/run-locally.py, .github/actions/run-tests/test_runner/argument_parser.py, CHANGELOG.md
This just enables remote debugging of the python script during test runs in case a problem occurs
=> Enable debugging of the test environemnt

CHANGELOG.md, src/components/SearchResults.vue
Backport fix of issue #1891.
_None_
=> Fix/1891 nasty flashing when finishing xhr requests v0.10

CHANGELOG.md, src/components/Modals/SettingsDialog.vue
=> Provide translatable string in Transifex

CHANGELOG.md, src/components/RecipeView/RecipeView.vue
This is a manual backport of #1944.
=> Backport of #1944: fix entry recipe yields

CHANGELOG.md, src/components/RecipeView/RecipeIngredient.vue, src/components/RecipeView/RecipeView.vue
This is a manual backport of #1945
=> Backport of #1945: hide UI elements in printout

CHANGELOG.md, src/components/Modals/SettingsDialog.vue
=> fix: Fix error when changing the update interval in the settings.

CHANGELOG.md, src/components/AppControls/AppControls.vue
=> fix: Use correct string of search input for search URL

CHANGELOG.md, src/components/FormComponents/EditTimeField.vue
=> fix(Recipe editing): Show initial value in time-edit fields

docs/user/index.md
Not much but it was bothering me.
Documentation
I just fixed a small typo in the docs
=> Fix. Small typo in docs

package-lock.json
This is just a maintenance PR to handle the can I use database.
=> Update CanIUse database using npx

CHANGELOG.md, package.json
Created PR from automatically generated commit
=> Update npm and node engines versions

package-lock.json
This should update the transition packages involved in the development to their corresponding latest versions according to `npm update`.
=> Update transient packages

CHANGELOG.md, src/components/FormComponents/EditMultiselect.vue, src/components/FormComponents/EditMultiselectInputGroup.vue
=> Add workaround to edit formulars as well

CHANGELOG.md
#2225 was wrongly credited to me
N.A.
=> chore: fix changelog credits

.changelog/current/2319-no-redownload-img.md, lib/Service/RecipeService.php
=> Only download recipe if change in URL was detected

.github/actions/run-tests/reset-from-container.sh
=> Provide the database name while restoring

.changelog/current/2345-hotfix-quotes-in-json-import.md, lib/Helper/HTMLFilter/HtmlEntityDecodeFilter.php, tests/Unit/Helper/HTMLParser/HttpJsonLdParserTest.php, tests/Unit/Helper/HTMLParser/res_JsonLd/caseK.html, tests/Unit/Helper/HTMLParser/res_JsonLd/caseK.json, tests/Unit/Helper/HTMLParser/res_JsonLd/caseK.json-graph, tests/Unit/Helper/HTMLParser/res_JsonLd/caseK.src
This is just a hot fix for #1077 hoping not to break many things.
As already mentioned in the issue, the real solution would be to fix the parser (#1675 #1110).
=> Create hotfix to avoid parsing of &quot; in JSON strings

.changelog/current/2391-maintenance-ws-dependency.md, package-lock.json
This is just a quick audit fix of a vulnerability. The problem is not in the live code but just the dev environment, so no big deal anyways.
=> Remove vulnerable ws dev dependency

.changelog/current/2500-fix-accedd-to-unknown-id.md, lib/Helper/Filter/JSON/RecipeIdTypeFilter.php
=> Fix the access to the array entry if not existing

.changelog/current/2512-update-lint-php-versin.md, .github/actions/php-linter/Dockerfile
We need to use current PHP 8.1 for linting.
=> Fix version of php version linter

.changelog/current/2511-updae-nc-version.md, .github/actions/deploy/appinfo/info.xml.dist, appinfo/info.xml
This just marks the app as compatible with NC 31
No RC yet published.
=> Update app to be formally compatible with NC 31

.github/workflows/build-test-images.yml, .github/workflows/deploy-appstore.yml, .github/workflows/pages.yml, .github/workflows/publish-test-results.yml, .github/workflows/pull-checks.yml, .github/workflows/tests.yml
This is a quick maintancne to fix some issues in GH actions
=> Maintenance of github actions

.changelog/current/2674-bump-nc-version.md, .github/actions/deploy/appinfo/info.xml.dist, appinfo/info.xml
This is just a quick fix for #2667.
Not thoroughly tested but seems to work on NC32 (aka master).
=> Mark app as compatible with NC31 (and 32 for dev)

.changelog/current/2839-update-npm-deps.md, package-lock.json, package.json
Update all NPM dependencies using CLI
=> Update all dependencies as known
