- appinfo/info.xml
https://apps.nextcloud.com/apps/cookbook buttons for issues & features link to the old gitlab-repo (which doesn't exist anymore because 404 is given)
I hope this updates those links.
> link to bugs-site from gitlab to github

- js/script.js
- templates/content/edit.php
- templates/content/recipe.php
- templates/navigation/index.php
- templates/navigation/recipes.php
- templates/settings/index.php
- translationfiles/de/cookbook.po
Worked along https://docs.nextcloud.com/server/stable/developer_manual/app/view/l10n.html with manual process. If @mrzapp  wants to use transifexit might be better if you do it.
This is related to issue #21.
I did not write any documentation how to generate the translation files. Also I did not check in the generated pot and js files into git. You might want to define a best practice here.
> Added support for translations

- lib/Service/RecipeService.php
It seems that the images are not loaded if there is a space in the name. [Example of a recipe with the problem.](https://www.colruyt.be/fr/recette/chipolatas-de-campagne-et-pennes-au-celeri)
> Replace spaces in img url as %20

- README.md
- appinfo/info.xml
- translationfiles/README.md
Triggered by #75.
@mrzapp There is a change in `appinfo/info.xml` with a broken link to an old image URL. I do not know if this will break the presentation in the appstore....
> Removing any reference to the master branch in documentations' links

- translationfiles/de/cookbook.po
- translationfiles/de_DE/cookbook.po
The word "All" in the list of keywords / categories wasn't translated. I hope, this is the right way doing it.
> German translation of "All"

- translationfiles/de/cookbook.po
> Typo: ein -> eine

- lib/Controller/PageController.php
I searched the templates for any usage of the "all_recipes" or the
"current_node" variable and did find nothing. Deleting them has no
noticeable effect.
> Removed unused variables

- js/script.js
- templates/content/edit.php
This should fix the bug mentioned in #108 
While [searching](https://stackoverflow.com/questions/23569073/button-onclick-fires-when-enter-key-is-pressed-in-input-text-field-in-ie) i found out that it is expected behavior that a button in a form catches all "enter" calls and interprets them as "clicks" except if the button is specifically defined as a button.
The Filepicker name for the Recipe Image was wrong and was therefore double confusing.
> Feature/enter opens image selection#108

- lib/Service/RecipeService.php
This fix should ignore the year, month and day values inside a time string and removes the debug `_test` values.
> Fix cookTime, prepTime and totalTime are reset to 00:00

- templates/content/recipe.php
When importing and editing recipes, if you end up with 0 values for
the cook or prep times, the recipe page will show big boxes displaying
unhelpful 0 values.  This commit omits those boxes as needed.
I offer this code under the terms of the AGPLv3 or any later version.
> Hide zero times

- appinfo/info.xml
- css/style.css
- js/script.js
- templates/content/edit.php
- templates/settings/index.php
In order to add more settings for #161, I wanted to improve the look of current settings, so I used a tooltip to display the last update time.
And to do that, I created a shared `.input-group` class with an `.input-group-addon`, (based on bootstrap3 vocabulary) and replaced the current `.list-item-tools`.
I also removed the `max-height` on buttons in this case, so that they fit textarea height, which looks better IMO (see screenshot below). But I guess that's not for me to decide ultimately :)
Also, I fixed button borders on hover.
Looking forward to your comments!
> Improve input groups and use one for update interval setting hint

- appinfo/info.xml
First: thank you for this useful Nextcloud app!
This is a detail but it is useful to get a link to this repo, e.g. to
check the ChangeLog (last commits), the code, etc.
We can see this link from https://apps.nextcloud.com/apps/cookbook
but also in Netcloud settings.
> appinfo: add link to the website

- src/components/AppNavi.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView.vue
Simple fix to avoid possible duplicate field keys in recipe instructions, tools and instructions.
Includes fix for #168 and #183
> Avoid duplicate field key

- src/components/AppNavi.vue
- src/components/RecipeEdit.vue
Resolves #168 and #183 (merge my other pull request first)
This performs just a crude refresh of the router view. For a more sophisticated solution (like only reloading the recipes and not the whole view, which would avoid the view flashing empty for a split second) some more fine-grained checking would be needed.
> Reload recipes after rescan

- lib/Service/RecipeService.php
I found that on allrecipes.com the last element of the array is the actual recipe object.
This fix searches through all elements of the json object found, if it is an array. Previous solution was to just pick the first object, which in the particular case would get a BreadCrumb object. If no recipe object is found, the last element is selected (instead of first) which should have no impact as the next check will say that it (still) isn't a recipe object and continue the outside for loop.
I checked that this worked on my installation, running NextCloud 18. Still I'm new here so please verify before merging!
> Fix when json object is an array

- README.md
- src/components/RecipeView.vue
I often view the recipes on my phone, and if the description is long it breaks the layout (everything else word wraps nicely).
I suggest pre-line here since it seems that's what you used for e.g. instructions, but maybe you think another wrapping is more sensible.
I could also have filed an issue report but it's fun to see if I manage to fix myself :) Seemed to work
Edit: And thanks a bunch for creating this app, loving it! In particular loading recipe from url is brilliant.
> Word wrap description when necessary

- lib/Service/RecipeService.php
Added the ability to preserve forward slashes in cleanUpString, so we may have ingredients with fractional amounts.
> Issue #262

- lib/Service/RecipeService.php
According to https://schema.org/recipeYield the yield value is specified like "recipeYield": "1 loaf"
The suggested RegEx  /(\d*)/ is a more generic approach to find digits in the recipeYield string instead of  /^.*?(\d*)/ 
For example this works for chefkoch.de ("recipeYield": "6 Portion(en)") and fittastetic.com ("recipeYield": ["2","2 Portionen"]).
The old RegEx /^.*?(\d*)/ worked on chefkoch.de but not e.g. on fittastetic.com
Because we have the if function in the next line (221) that deals with several occurrences and picks the first one, it should be save to do it that way.
> Change RegEx for yield value to match digits in json-ld less restrictive

- .codecov.yml
- .github/actions/run-tests/README.md
- .github/actions/run-tests/action.yml
- .github/actions/run-tests/tests/install.sh
- .github/actions/run-tests/tests/test-entrypoint.sh
- .github/workflows/tests.yml
- Makefile
- phpunit.integration.xml
- phpunit.xml
This PR should extend the existing github testing workflow by uni and integration testing, code coverage analysis and tarball creation. This is a second step towards #233 but requires more knowledge about the format or files involved in the market place. Thus, here it is only a first attempt.
> Enhanced the Github action workflows

- lib/Service/RecipeService.php
Some json recipes (like on https://www.colruyt.be/fr/en-cuisine/meli-melo-de-legumes-oublies-au-chevre) don't contain the array directly, but have it inside the 'itemListElement'. While this is clearly a mistaken understanding of the spec, this is a workaround that shouldn't impact existing json parsing.
Thank you very much for the project and the work !
> Add workaround for recipeInstructions

- .codecov.yml
- .github/actions/run-tests/action.yml
- .github/actions/run-tests/tests/test-entrypoint.sh
- .github/workflows/tests.yml
Currently the paths in codecov are off due to interferences with the main nextcloud server git repository. This should solve things.
> Repair codecov integration

- composer.json
Today Composer 2 was released and it requires the package name to be of a certain structure. This was a warning unser the old composer 1.x but now failed the CI builds.
> Make name of package compatible with composer 2

- composer.json
- lib/Service/RecipeService.php
This PR improves how libxml errors are handled. Because there can be a lot of duplicate errrors I decided to count similar errors and show how often it occurred. The log output for multiple failure looks like this:
```
{"reqId":"EYcnDGGmhWZ8kXC4Te7E","level":2,"time":"2020-10-25T18:02:51+00:00","remoteAddr":"2a02:810d:640:1e52:3f8c:68c2:b41d:b462","user":"max","app":"no app in context","method":"POST","url":"/index.php/apps/cookbook/import","message":"libxml: Error 68 occurred 907 times while parsing https://www.chefkoch.de/rezepte/18711004787789/Risotto-mit-gruenem-Spargel-und-Parmesan.html. Last time in line 7728 and column 119: htmlParseEntityRef: no name\n","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.4.2"} …
```
> Handle libxml errors and warnings

- lib/Db/RecipeDb.php
- src/components/AppControls.vue
- src/components/AppNavi.vue
Added item for viewing uncategorized recipes in the navigation.
Closes #326
> Allow selecting recipes with unassigned category

- .github/workflows/changelog.yml
- CHANGELOG.md
> Add a changelog

- CHANGELOG.md
- lib/Service/RecipeService.php
If the recipe folder is not specified explicitly in the config, it should be stored nevertheless. Otherwise the folder is changed if the language of the user is changed. This will cause a stale database and needs reindexing.
This PR will store the setting in the configs if no config was found. If the user wants to move the/rename the folder it is up to his manual work.
> Make the folder name persistend under changes of the language

- CHANGELOG.md
- README.md
I added the two Android clients I found to the main README to make them easily discoverable by users. This list can be extended if there are more clients (also for other OSes).
Closes #319
> Added known Android Clients to README

- .github/actions/run-tests/tests/install.sh
- CHANGELOG.md
- composer.json
We have to be compatible with the phpunit framework version chosen by the NC server. Otherwise we get warnings and other issues during code testing.
> Update phpunit framework to most recent version

- CHANGELOG.md
- appinfo/routes.php
- lib/Controller/MainController.php
- lib/Db/RecipeDb.php
- lib/Service/RecipeService.php
- src/components/AppControls.vue
- src/components/RecipeKeyword.vue
- src/components/RecipeView.vue
- src/components/SearchResults.vue
- src/router/index.js
Added list of keywords below the title in the recipe view. Klicking keyword routes to recipe list with corresponding tag.
Closes #247
> Added tag/keyword cloud to recipe view

- CHANGELOG.md
- src/components/RecipeEdit.vue
Creating new recipes is currently not working since the `recipe` variable is null. This PR should fix it.
> Fixes null when creating new recipe

- CHANGELOG.md
- src/components/EditInputGroup.vue
- src/components/RecipeEdit.vue
In the recipe editor, pasting content with newlines in a tools or ingredients field automatically creates new fields.
For textareas (recipe steps) this is not done.
Closes #325.
> Parse multiline ingredients and tools into separate fields

- CHANGELOG.md
- lib/Db/RecipeDb.php
- src/components/AppIndex.vue
- src/components/RecipeKeyword.vue
- src/components/SearchResults.vue
Regarding #188.
Added tag cloud between the breadcrumb nav and the recipe overview grid. What it currently does, is
- show all keywords of the displayed recipes
- keywords are selectable
- selecting one or multiple keywords shows only recipes in the current category/search that have all keywords attached
- I changed the backend in such a way that not only the recipe name and id are returned anymore, but also a comma-separated string of keywords. The idea is to prevent querying the keywords of each recipe but only having a single database call.
- I wasn’t able to get a `GROUP_CONCAT` working with the QueryBuilder. This might be more efficient than my workaround, so if anyone knows how to get this working - feel free to contribute! 
Feedback, as always, welcome.
> Show tag cloud in search results

- CHANGELOG.md
- lib/Service/JsonService.php
This is a first attemt to simplify the codebase (minimally). It is a set of shortcuts to handle JSON strings containing data of schema.org objects.
> Added a basic version of a JSON service

- .github/actions/run-tests/tests/Dockerfile
- .github/actions/run-tests/tests/xdebug.config
- CHANGELOG.md
Due to a new version in xdebug, we need to tweak CI settings a bit.
> Enabled coverage checking using new xdebug 3

- CHANGELOG.md
- src/components/SearchResults.vue
Hotfix for #425 . Keyword filter is reset on route update.
> Clear keyword filter when switching route (e.g., between categories)

- .github/actions/run-tests/tests/test-entrypoint.sh
- .github/workflows/tests.yml
- CHANGELOG.md
- Makefile
- appinfo/info.xml
- lib/Db/RecipeDb.php
- lib/Service/DbCacheService.php
- lib/Service/JsonService.php
- lib/Service/RecipeService.php
This PR implements two functions
- Run the NC code checker on the app code to ensure the code requirements are met.
- Build a valid installation tarball during CI runs
> Add code checker tests in CI and build correct deployment files in CI

- CHANGELOG.md
- lib/Service/DbCacheService.php
Remove bugs to allow working on current NC version. See also https://github.com/nextcloud/cookbook/issues/419#issuecomment-743369346
> Removed typos from refactory

- .github/actions/deploy/create-version.sh
- .github/workflows/deploy-test.yml
- CHANGELOG.md
The auto-release CI is non-functional for two reasons:
1. The test on version trigger is not only checked on the merge message but all messages involved.
2. Signature is rejected by the app store.
This PR should cover these issues.
> Fix CI bugs

- CHANGELOG.md
- src/components/EditMultiselect.vue
- src/components/RecipeEdit.vue
This PR adds a NC-styled `Multiselect` element for keywords and categories for faster insertion.
There is some collision with PR #386 but only for the keyword and category selection, which should be replaced by this one if accepted.
Closes #313 although for the future we might want to consider adding something similar for selecting ingredients, keywords, and tools as mentioned in the issue
> Added multiselection for categories and keywords to recipe editor

- CHANGELOG.md
- src/components/RecipeIngredient.vue
When hovering over the ingredients, these can be marked as checked. This is only temporary until the page is reloaded.
Closes #385
> Added option to check ingredients

- CHANGELOG.md
- l10n/de.js
- l10n/de.json
- l10n/de_DE.js
- l10n/de_DE.json
- l10n/en_GB.js
- l10n/en_GB.json
- lib/Service/RecipeService.php
- package.json
- src/components/RecipeView.vue
Regarding #131, I added schema.org Recipe’s `dateCreated` and `dateModified` fields to the recipe view.
These also set/updated when creating or updating a recipe.
The recipe view 
- shows the created date if available
- shows the modified date if its
- available
- not the same as the dateCreated timestamp
Date & time are localized.
> Support dateCreated and dateModified fields

- CHANGELOG.md
- src/components/EditImageField.vue
- src/components/EditInputField.vue
- src/components/EditInputGroup.vue
- src/components/EditTimeField.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView.vue
I noticed that the editing components (`EditInputField`, `EditInputGroup`, etc.) are tightly coupled with `RecipeEdit` due to the references from the child to the parent component. As an example, look at the `EditInputField` component which sets a field in the `$parent`.
In this PR I removed the tight coupling which should allow/lead to
- a clear one-way dependency of those components
- more flexible ways of data binding
- v-model can be used on those components
- components can be reused in different places.
@sam-19 Could you have a look at this?
> Removing tight coupling in recipe-editing vue components

- CHANGELOG.md
- lib/Db/RecipeDb.php
- src/components/AppIndex.vue
- src/components/RecipeKeyword.vue
- src/components/RecipeView.vue
- src/components/SearchResults.vue
I made some changes to improve the keyword filtering in the recipe-list view. With this PR
- keywords show number of recipes that have the keyword assigned
- keywords are ordered by the number
- when keywords are selected, non-selectable keywords are moved to the end of the list
- selected keyword are moved to the beginning of the list for easy discovery
- a maximum size for the keyword-selection area is defined to prevent the page getting cluttered with many keywords. The area can be scrolled vertically to allow access to all keywords.
@sam-19 maybe you can review this PR?
> Improved Keyword filtering

- CHANGELOG.md
- src/components/LazyPicture.vue
> Prevent img loaded event being handled twice

- CHANGELOG.md
- src/components/RecipeEdit.vue
When changes in the recipe form are done by the user, the form is marked dirty. When navigating away from a dirty form, the user is prompted for confirmation.
Closes #310
@sam-19 If you‘d like to share your opinion, you‘re welcome!
> Warn before leaving recipe editor with changes

- CHANGELOG.md
- src/components/AppNavi.vue
> Remove non-functional info button from settings

- CHANGELOG.md
- lib/Db/RecipeDb.php
> Remove keywords upon removal of recipe

- .github/actions/deploy/fill-in-data.sh
- CHANGELOG.md
- appinfo/routes.php
- lib/Controller/MainController.php
Especially for 3rd party integrations, it is required to define an API version to clear the possible API endpoints.
> Create an API endpoint to get the API version

- CHANGELOG.md
- src/components/AppNavi.vue
> Corrected URL endpoint to load categories correctly

- CHANGELOG.md
- css/style.css
- src/components/RecipeNutritionInfoItem.vue
- src/components/RecipeView.vue
> Updates color in nutrition info and removes bullet point

- CHANGELOG.md
- src/components/RecipeIngredient.vue
- src/components/RecipeView.vue
Depending on the existence of subgroups in the ingredient list (starting with ##) the ingredients are more or less indented. 
The vertical overlap of checkmark and ingredient text, that appeared when there was a line break in the text, is removed.
Also a hanging indent is introduced to make it visually clear when there is a line break within a single ingredient.
Previously:
With subgroup:
Without subgroup:
> Update ingredient list visuals

- CHANGELOG.md
- README.md
My qutebrowser userscript just got merged.  Let me know if this is too niche.
> add qutebrowser userscript

- CHANGELOG.md
- lib/Controller/ConfigController.php
- lib/Controller/MainController.php
- lib/Controller/RecipeController.php
- lib/Helper/RestParameterParser.php
This should make implementing new endpoints simpler and reduces the probability of errors.
> Create a central class for parsing of AJAX parameters in POST/PUT

- CHANGELOG.md
- package.json
- src/components/AppControls.vue
- src/components/AppIndex.vue
- src/components/AppNavi.vue
- src/components/EditInputGroup.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView.vue
- src/components/SearchResults.vue
- src/main.js
As NC is dropping the support for the global jQuery and including the library within our app seems to be a bit of an overkill, I replaced the jQuery ajax calls by @nextcloud/axios and switched to plain JS in some places.
Closes #475
> Remove jQuery

- CHANGELOG.md
- lib/Helper/RestParameterParser.php
> Removed str_starts_with and str_end_with calls

- CHANGELOG.md
- src/components/RecipeView.vue
see discussion in #497, [here](https://github.com/nextcloud/cookbook/pull/497#discussion_r558283466)
> Introduces recipe as computed property in RecipeView

- CHANGELOG.md
- lib/Db/RecipeDb.php
- src/components/AppIndex.vue
- src/components/RecipeList.vue
- src/components/SearchResults.vue
also returns keywords for tag searches
> Split off recipe list to single component

- CHANGELOG.md
- src/components/RecipeTimer.vue
- src/components/RecipeView.vue
- Timers are hidden for zero time
- Fixed missing timer update after saving recipe changes
Closes #539
> Hide timers for t=0

- CHANGELOG.md
- src/components/AppControls.vue
- src/components/AppMain.vue
- src/components/AppNavi.vue
- src/store/index.js
- Removed navigation toggle next to breadcrumbs
- Introduced left-navigation-pane visibility state to Vuex store
- toggling navigation state via Vuex instead of querying for element ids
Closes 514, closes 534
> Fix some navigation pane issues

- CHANGELOG.md
- src/components/AppNavi.vue
> Refreshing left navigation pane after downloading new recipe data from URL

- CHANGELOG.md
- lib/Service/JsonService.php
- tests/Unit/Service/JsonServiceTest.php
The class JsonService did not check if a `@context` was given. This should cover that case.
> Check context of JSON objects

- CHANGELOG.md
- appinfo/routes.php
- lib/Controller/MainController.php
- package.json
- src/components/AppNavi.vue
- src/components/AppNavigationCaption.vue
- src/components/RecipeEdit.vue
- src/components/SearchResults.vue
- src/store/index.js
- webpack.config.js
- added API endpoint (`'url' => '/api/category/{category}', 'verb' => 'PUT'`)
- made categories in navigation pane editable
Closes #322
> Renaming category

- CHANGELOG.md
- src/components/AppNavi.vue
- src/components/EditInputField.vue
- src/components/EditInputGroup.vue
- src/components/EditMultiselectPopup.vue
- src/components/RecipeEdit.vue
- src/components/RecipeIngredient.vue
- src/components/RecipeInstruction.vue
- src/components/RecipeTool.vue
- src/components/RecipeView.vue
Added functionality to reference other recipes by id in description, tools, ingredients, and instructions
- In recipe editor, when entering '#' a popup with a multiselect is shown that allows selecting a reference.
- the popup is shown in fullscreen for small window widths
- When selecting a recipe a reference is entered: `#r/123`
- in recipe viewer this is converted to `#123` linking to the recipe page
Closes #209
> Reference recipes

- CHANGELOG.md
- src/components/EditInputGroup.vue
- webpack.config.js
- Add button to insert tool, ingredient, and instruction entry above existing entry in recipe editor
- Fixed CSS and SCSS webpack configuration of css-loader
Closes #571
> Insert tool, ingredient, and instruction in between existing ones

- .github/actions/run-tests/mysql/Dockerfile
- .github/actions/run-tests/tests/Dockerfile
- CHANGELOG.md
Add a maintainer according to docker image guidelines
> Update dockerfile with maintainer

- CHANGELOG.md
- lib/Controller/ConfigController.php
- lib/Controller/MainController.php
- lib/Exception/UserFolderNotWritableException.php
- lib/Service/RecipeService.php
- src/components/AppInvalidGuest.vue
- src/guest.js
- templates/invalid_guest.php
- webpack.config.js
If the user folder is not writable as typically for a guest account, the cookbook app has hight probability of being non-functional. Yet, there are no useful error messages or ways to tackle the problem. Instead a stacktrace is generated.
This should get this issue covered.
Closes #468
> Allow access of guest accounts

- CHANGELOG.md
- docs/dev/deployment.md
Make documentation compatible to script.
> Corrected keywords for deployment

- .eslintignore
- .eslintrc.yml
- .prettierignore
- .prettierrc.json
- .stylelintrc.yml
- CHANGELOG.md
- package.json
Currently, this only inserts a code styler in NPM scripts and registers the corresponding packages in the `package.json`. The CI is **not** affected as the changes would be quite big.
> Added scripts to prepare the Vue code styler

- CHANGELOG.md
- appinfo/routes.php
- lib/Controller/MainController.php
We have still some old API endpoints that should be cleaned up. This PR should clean up no longer used routes and structure the code better.
> Deprecate some routes by comments

- .github/workflows/tests.yml
- .stylelintrc.yml
- CHANGELOG.md
- src/components/AppControls.vue
- src/components/AppInvalidGuest.vue
- src/components/AppMain.vue
- src/components/AppNavi.vue
- src/components/AppNavigationCaption.vue
- src/components/AppSettings.vue
- src/components/EditImageField.vue
- src/components/EditInputField.vue
- src/components/EditInputGroup.vue
- src/components/EditMultiselect.vue
- src/components/EditMultiselectInputGroup.vue
- src/components/EditMultiselectPopup.vue
- src/components/EditTimeField.vue
- src/components/LazyPicture.vue
- src/components/RecipeEdit.vue
- src/components/RecipeImages.vue
- src/components/RecipeIngredient.vue
- src/components/RecipeInstruction.vue
- src/components/RecipeKeyword.vue
- src/components/RecipeList.vue
- src/components/RecipeNutritionInfoItem.vue
- src/components/RecipeTimer.vue
- src/components/RecipeView.vue
This should enforce a stricter CSS styling using stylelint.
Most of the changes are automatically generated but few manual adjustments were needed to make the style linter happy.
> Enable stylelint to keep CSS codes clean and tight

- .github/workflows/build-test-images.yml
- CHANGELOG.md
In private repositories the secrets are unknown and thus the nightly build fails. This extension should prevent the nightly build if any secret is missing or an empty string.
> Disable testing in repos without secrets

- .php_cs.dist
- CHANGELOG.md
Currently, the CS fixer descends as well into some folders that are going to be filtered out later. This is not optimal from a performance perspective but as well causes issues when the permissions are not well set (in the testing environment).
> Do not only filter but exclude paths from search

- CHANGELOG.md
- src/components/RecipeIngredient.vue
- src/components/RecipeInstruction.vue
- src/components/RecipeView.vue
- src/main.js
> Fixes minor errors in displaying ingredients and instructions

- CHANGELOG.md
- src/components/RecipeEdit.vue
> Fix missing translation

- CHANGELOG.md
- lib/Controller/MainController.php
- src/components/AppNavi.vue
This solves partially the issue described in #626 as it avoids an empty alert box.
> Show error message upon import exception

- CHANGELOG.md
- lib/Controller/ConfigController.php
- lib/Controller/MainController.php
- lib/Controller/RecipeController.php
- lib/Db/DbTypesPolyfillHelper.php
- lib/Db/RecipeDb.php
- lib/Exception/InvalidJSONFileException.php
- lib/Exception/UserFolderNotWritableException.php
- lib/Helper/RestParameterParser.php
- lib/Migration/Version000000Date20190312140601.php
- lib/Migration/Version000000Date20190910100911.php
- lib/Migration/Version000000Date20190910223344.php
- lib/Migration/Version000000Date20200315121603.php
- lib/Service/DbCacheService.php
- lib/Service/JsonService.php
- lib/Service/RecipeService.php
- tests/Integration/AppTest.php
- tests/Unit/Service/JsonServiceTest.php
- tests/Unit/Service/ValidateDurationTest.php
This should cover the issues regarding the new code styling issues
> Updated styling of code according to cs fixer

- CHANGELOG.md
- package.json
The `@nextcloud/capabilities` in version `1.0.3` causes issues with the `@nextcloud/vue` library. This is a hotfix to keep the problem at bay for now.
> Added explicit version of dependency as workaround

- CHANGELOG.md
- lib/AppInfo/Application.php
- lib/Search/Provider.php
This fixes #559 by implementing a search provider for a unified search. Matching recpies are listed with their thumbnail (if available) and title, as well as the category if applicable.
The subline listing the category could easily be replaced by the recipe description, I am open for suggestions here. But I want to note that the current category lookup is expensive, as we read it from the recipe JSON file. Is that okay, or should we handle it differently?
> Implement unified search provider

- CHANGELOG.md
- src/components/EditInputGroup.vue
Fixes the missing part of #648.
Closes #670
> Showing recipe-ref popup in input groups on # (keyboard-layout independent)

- CHANGELOG.md
- lib/AppInfo/Application.php
- lib/Controller/ConfigController.php
- lib/Controller/MainController.php
- lib/Controller/RecipeController.php
- lib/Db/DbTypesPolyfillHelper.php
- lib/Db/RecipeDb.php
- lib/Exception/InvalidJSONFileException.php
- lib/Exception/UserFolderNotWritableException.php
- lib/Helper/RestParameterParser.php
- lib/Migration/Version000000Date20190312140601.php
- lib/Migration/Version000000Date20190910100911.php
- lib/Migration/Version000000Date20190910223344.php
- lib/Migration/Version000000Date20200315121603.php
- lib/Search/Provider.php
- lib/Service/DbCacheService.php
- lib/Service/JsonService.php
- lib/Service/RecipeService.php
- tests/Integration/AppTest.php
- tests/Unit/Service/JsonServiceTest.php
- tests/Unit/Service/ValidateDurationTest.php
Corrected style changes applied in a69938d.
> Corrected styling in PHP files

- CHANGELOG.md
- package.json
The dependency was merged only as a workaround for a bug in the dependency. This should revert that change.
> Removed obsolete dependency @nextcloud/capabilities

- .github/workflows/stale.yml
- CHANGELOG.md
This will enable a stale bot using workflow files for issues and PRs.
> Activating stalebot

- CHANGELOG.md
- lib/Controller/MainController.php
- lib/Controller/RecipeController.php
- lib/Exception/RecipeExistsException.php
- lib/Service/RecipeService.php
- src/components/AppNavi.vue
- src/components/AppSettings.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView.vue
- src/store/index.js
> Generate clear message when recipe exists during creation

- CHANGELOG.md
- lib/Service/RecipeService.php
> Correct handling of arrays on recipeYields property

- .github/workflows/stale.yml
- CHANGELOG.md
This should remove a wrong `<` symbol from the messages by the stale bot.
> Update the stale workflow

- CHANGELOG.md
- package.json
This will remove an unneeded NPM dependency as far as I can see.
This dependency seems to be a leftover of the original implementation work and (currently) is references nowhere in the codebase.
> Remove unneeded dependency

- .github/workflows/tests.yml
- CHANGELOG.md
This should fix some issues with codecov reports. See https://github.com/codecov/codecov-action/issues/190.
> Correct fetching depth in action scripts

- .l10nignore
This is a fix for 6a520cb4 to get also future swagger JS files.
> Corrected path from l10n ignore file

- README.md
This is a very small PR that just adds nextcloud-cookbook-flutter F-Droid link in README
> Add Cookbook-flutter FDroid link

- .github/actions/run-tests/docker-compose.yml
- .github/actions/run-tests/run-locally.sh
- .github/actions/run-tests/tests/entrypoints/default-entrypoint.sh
- .github/actions/run-tests/tests/xdebug.config
- CHANGELOG.md
This is an extension to #774 to fix some minor issues.
> Fix some missing fucntionality from PR 774

- .github/actions/run-tests/reset-from-container.sh
- .github/actions/run-tests/run-locally.sh
- .github/actions/run-tests/run-occ.sh
- CHANGELOG.md
- lib/Migration/Version000000Date20210701093123.php
- phpunit.integration.xml
- phpunit.xml
- tests/Integration/Setup/Migrations/Version000000Date20210701093123Test.php
- tests/bootstrap.php
This should fix the problems in the recent migrations regarding old data in the tables that cause trouble with the indices.
Closes #763
Closes #762
> Fix/763: Tidy up database on migration

- .github/actions/run-tests/run-locally.sh
- .github/actions/run-tests/tests/Dockerfile
- .github/actions/run-tests/tests/entrypoints/test.sh
- CHANGELOG.md
- tests/Integration/Setup/Migrations/AbstractMigrationTestCase.php
- tests/Integration/Setup/Migrations/Version000000Date20210701093123Test.php
- tests/bootstrap.php
This should simplify the writing of migration tests.
> Create an abstract class for all migration test casees

- README.md
Add documentation to describe a method to clear/reset the database where recipies are shown from in addition to the "try rescanning" method.
this is based on a conversation from Element and my personal experience updating my cookbook instance to support NC 22
> expand "cant see recipes" troubleshooting in README

- .hooks/README.md
- .hooks/pre-commit
- CHANGELOG.md
- Makefile
- composer.json
- lib/Service/DbCacheService.php
> Hotfix to avoid error on trim invocation

- .github/workflows/tests.yml
- CHANGELOG.md
- Makefile
- package.json
- src/components/AppControls.vue
- src/components/AppNavi.vue
- src/components/RecipeCard.vue
- src/components/RecipeEdit.vue
- src/components/RecipeInstruction.vue
- src/components/RecipeList.vue
- src/components/RecipeTool.vue
This should remove some of the warnings at the npm building during the GH action runs.
> Some repair steps for the github actions

- .eslintrc.yml
- .gitignore
- .hooks/pre-commit
- .hooks/pre-push
- CHANGELOG.md
- package.json
> Split checking hooks into commit and push

- .hooks/pre-commit
- .hooks/pre-push
- CHANGELOG.md
This is just a small enhancement to #851.
> Allow hooks to run all checks before terminating

- CHANGELOG.md
- src/components/AppSettings.vue
- src/components/EditImageField.vue
- src/components/RecipeEdit.vue
This should fix some issues with the translations by transifiex
> Corrected lines intended for transifex translations

- CHANGELOG.md
- package.json
- templates/index.php
- webpack.config.js
- webpack.devel.js
This should add two plugins to the build chain.
- The clean plugin will tidy up the `js` folder on each build.
- The mini-css-extractor will build a dedicated CSS file to enhance load speed.
> All NPM plugins

- CHANGELOG.md
- templates/invalid_guest.php
Removed a bug introduced in #868.
> Removed bug in guest template

- CHANGELOG.md
- src/components/RecipeEdit.vue
- src/components/RecipeTimer.vue
- src/components/RecipeView.vue
- webpack.config.js
> Add time unit labels

- CHANGELOG.md
- src/components/AppControls.vue
Make the buttons always visible so that they are accessible even when
scrolled halfway down a recipe.
This is consistent with the "Open navigation" / "Close navigation" button and gives more information and controls than making the bottom save button sticky.
> Make AppControls breadcrums sticky (#834)

- CHANGELOG.md
- src/components/EditInputGroup.vue
I noticed this while trying to implement something else.
When pasting multiple lines, the empty lines should be filtered out before checking if only one line was pasted, shouldn't they?
For example, if the following is pasted: `"this is a test\n"`, this will be split into `["this is a test", ""]` and `this.singleLinePasted` will be false even though later the empty item will be filtered out and the array will contain a single element.
I also replaced the for loop with the filter method, I hope that's ok. I think it's more clear what is going on.
> Filter empty pasted lines before single line check

- CHANGELOG.md
- src/components/AppControls.vue
Fix #888 where the appcontrol breadcrums were given a position based on the hard-coded value `50px`. Instead, use the variable `--header-height` so that this code is adapted if the header height changes..
> Use var(--header-height) not hard-coded 50px for breadcrums sticky position

- CHANGELOG.md
- src/components/EditInputGroup.vue
I was recently sent a recipe from a relative by email. Each instruction from the recipe started with ` -  ` (space hyphen space space). When I pasted this into Cookbook, I was very impressed when my clipboard was split by newline and multiple steps were inserted, but each line started with ` -  `. 
This pull request removes this common prefix when pasting multiple lines. First, the common prefix is found. Then, I disregard the rest of the prefix if I detect anything that is not punctuation or whitespace. This is because I do not want to remove anything that is not actual text. For example, if each line starts with `Step 1 is to ...`. Finally, the prefix is removed from each line.
Here are some examples:
These lines:
```
-   Put the frying pan on the stove
-   Add the oil to the frying pan …
```
> Remove the common prefix from pasted lines

- CHANGELOG.md
- src/components/RecipeEdit.vue
Fix the UI glitch with a tiny blob in the keywords field when loading a recipe with empty keywords. The bug was caused by `keywords.split(',')` when `keywords` is an empty string. This will create an array of a single element: an empty string. Rendering this empty string as a keyword results in this little blob. The solution is to filter out empty strings after the call to `.split()`.
> Fix the UI glitch when keywords are empty (#857)

- CHANGELOG.md
- src/components/EditInputGroup.vue
This is a fix for #882.
When enter is pressed in `EditInputGroup`, there is an attempt to select the next input field. This works for ingredients, which use inputs, but not for instructions, which use `textareas`. Now, both are searched for using `querySelector`.
> Enable enter to go to next instructions step

- CHANGELOG.md
- src/components/EditInputGroup.vue
Fixes #881.
Use a `keydown` event listener rather than a `keyup` event lister. This allows us to use `event.preventDefault()` when enter is pressed to go to the next textarea without adding a `\n` to the current textarea.
I believe the reason to use `keyup` previously was to not get repeat events. In order to make sure that repeat events are still not considered, we exit early if `event.repeat` is true.
I also took this opportunity to clean up some parts of the code.
First, I replaced `event.keyCode === 13` with `event.key === 'Enter'`. This was done for many reasons.
1. [`event.keyCode` is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)
2. `event.key === 'Enter'` is more readable than `event.keyCode === 13`. You do not have to lookup what 13 means.
3. …
> Prevent newlines switching input fields

- CHANGELOG.md
- src/components/EditInputGroup.vue
Fixes #898.
In `handleInput`, check if content was pasted using `event.inputType`. This uses the event as the source of truth, so that we don't need the call to `nextTick` nor to read attributes set by `handlePaste`.
In `handlePaste`, if a single line was pasted, emit just like `handleInput` was doing for a single line pasted.
Remove the attributes `contentPasted` and `singleLinePasted`.
All of this removes the tight coupling between `handleInput` and `handlePaste`. There is no longer a need for the two attributes
`singleLinePasted` or `contentPasted`.
I have tested it quickly, and everything seems to work as before.
> Remove tight coupling between input and paste

- CHANGELOG.md
- src/components/EditInputField.vue
Fixes #908 
Nextcloud core is setting global unscoped styles on any `div[contentedibtale]`. Such a div is used by our markdown editor:
CodeMirror. Fix this by overwritting Nextcloud core's heavy-handed global styles.
Now, adding `contenteditable="true"` does not change the style inside our markdown editor:
https://user-images.githubusercontent.com/8503756/157314618-a553dee7-6857-4f63-a949-9eb793d93201.mp4
> Revert Nextcloud core's contentedibtale styles

- CHANGELOG.md
- src/components/AppNavigationCaption.vue
- stylelint.config.js
Fixes #913 
This unfortunately adds two stylelint warnings:
```
WARNING in src/components/AppNavigationCaption.vue
195:15  ✖  Unexpected unknown function "math.div"  function-no-unknown
207:17  ✖  Unexpected unknown function "math.div"  function-no-unknown
```
See also: https://github.com/stylelint-scss/stylelint-config-recommended-scss/issues/92
> Fix SASS deprecations, replace / with math.div

- CHANGELOG.md
- src/components/EditInputGroup.vue
Fixes #905 
When refactoring they keydown handler of EditInputGroup, a regression was introduced where the # would not be inserted when linking to another recipe. This is because we previously had a keyup event listener, which cannot prevent the key from being insterted, but now we are using a keydown listener, which can. Therefore, the `e.preventDefault()` that was already present in the code now has unintended side effects. We can remove it, there is no reason to have it there.
> Don't prevent default event of inserting # when linking recipes

- CHANGELOG.md
- src/components/EditInputGroup.vue
Fixes #713 
Now, when multiple whitespace characters appear when pasting recipe ingredients, instructions, etc. they are replace by a single space.
> Trim multiple whitespace characters when pasting

- CHANGELOG.md
- lib/Helper/UserConfigHelper.php
- lib/Service/DbCacheService.php
- lib/Service/RecipeService.php
- tests/Unit/Helper/UserConfigHelperTest.php
This should encapsulate the access to the user settings.
> Extract the access to the user config in its own helper class

- .github/actions/run-tests/config/www/000-default.conf
- .github/actions/run-tests/config/www/apache2.conf
- .github/actions/run-tests/docker-compose.yml
- CHANGELOG.md
This is a preparation of the tests in #284, #459, and possibly more. This allows using PHP code in the test server (`www` container) to set the headers as needed.
> Use apache+PHP instead of plain nginx for HTTP test server

- .github/actions/run-tests/run-locally.sh
- .github/actions/run-tests/tests/entrypoints/test.sh
- CHANGELOG.md
This will clean up existing code coverage reports upon creating a new one (only the very last is removed to allow iterative testing/work). Additionally, also for failing tests the code coverage is stored accordingly instead of cluttering the file system.
> Enhance the unit test script a bit

- lib/Service/RecipeService.php
- lib/Service/ThumbnailService.php
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
> Correct spelling

- .hooks/pre-commit
- CHANGELOG.md
Closes #932
This seems to fix the problem for now. For complex changes (where you add a file and remove it from gitignore in one step), it might still fail.
> Also add untracked files in stash to prevent issues with deleted files

- .vscode/launch.json
- .vscode/settings.json
- CHANGELOG.md
- Makefile
- cookbook.code-workspace
This adds a default configuration to the codebase that allows to set up a complete development environment. A side effect is that the stash push/pop in the hool will not cause trouble with the IDE.
For now, the IDE is VS code. Other IDEs might be added if need arises.
> Add editor configuration to codebase

- CHANGELOG.md
- lib/Helper/ImageService/ThumbnailFileHelper.php
- tests/Unit/Helper/ImageService/ThumbnailFileHelperTest.php
Adding an image to a recipe without image causes the thumbnail generator to throw an exception.
> Fix bug that thumbnail file needs to be created if not yet existing

- CHANGELOG.md
- docs/dev/api/0.0.2/index.html
- docs/dev/api/0.0.3/index.html
- docs/dev/api/0.0.3/openapi-cookbook.yaml
- lib/Controller/RecipeController.php
- lib/Helper/AcceptHeaderParsingHelper.php
- tests/Unit/Controller/RecipeControllerTest.php
- tests/Unit/Helper/AcceptHeaderParsingHelperTest.php
Closes #954
This is a quick fix for issue #954. This checks the accept header and returns a 406 HTTP error in case no JPG file was found on the server,
This is not yet capable to support other image files (like PNG) but this is the first step toward multi-type image files. The multi-type must be implemented separately as it is a more involved change/refactor involved.
> Allow the client to specify the image type using Accept header

- CHANGELOG.md
- lib/Controller/RecipeController.php
See https://en.wikipedia.org/wiki/MIME
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>
> l10n: Change to uppercase

- CHANGELOG.md
- docs/dev/api/0.0.2/openapi-cookbook.yaml
- docs/dev/api/0.0.3/openapi-cookbook.yaml
> Fix the API specification to real behavior

- CHANGELOG.md
- lib/Service/RecipeService.php
> Quick fix to prevent long name of recipes

- .l10nignore
- CHANGELOG.md
> Removed some folders from translations

- CHANGELOG.md
- src/components/AppControls.vue
Fix #987 
Move the reload button out of the title button and into its own breadcrumb. This is a temporary solution. The permanent solution is to use some component other than breadcrumb, which is not designed for this.
> Fix refresh-icon overlays name of recipe

- .github/actions/check-todo/check.sh
- .github/workflows/pull-checks.yml
- CHANGELOG.md
Closes #1035
As this is related to PRs, I have to open this as a draft PR and test the progress. I will rebase in the end to have a neat and clear commit history. Thus, it is only considered WIP at the moment.
> Make PRs from forks possible again

- .github/workflows/pull-checks.yml
- CHANGELOG.md
- package-lock.json
- package.json
> Add code style checker for package.json file

- .github/actions/run-tests/config/www/000-default.conf
- .github/actions/run-tests/docker-compose.yml
- .github/actions/run-tests/run-locally.sh
- .github/actions/run-tests/www/Dockerfile
- .github/workflows/tests.yml
- CHANGELOG.md
- lib/Db/RecipeDb.php
- lib/Exception/NoDownloadWasCarriedOutException.php
- lib/Helper/DownloadHelper.php
- lib/Service/HtmlDownloadService.php
- tests/Integration/Helper/DownloadHelper/DownloadHelperTest.php
- tests/Integration/Helper/DownloadHelper/res/content-type.php
- tests/Integration/Helper/DownloadHelper/res/htaccess
- tests/Unit/Service/HtmlDownloadServiceTest.php
> Enable downloading using curl

- .github/actions/deploy/appinfo/info.xml.dist
- .github/actions/deploy/create-version.sh
- .github/workflows/tests.yml
- CHANGELOG.md
- appinfo/info.xml
This should speed up the fetching of artifacts during the CI runs.
> Only upload needed artifacts for CI

- CHANGELOG.md
- lib/Helper/HTMLParser/AbstractHtmlParser.php
- lib/Helper/HTMLParser/HttpJsonLdParser.php
- lib/Helper/HTMLParser/HttpMicrodataParser.php
- lib/Service/RecipeExtractionService.php
- lib/Service/RecipeService.php
- tests/Unit/Helper/HTMLParser/HttpJsonLdParserTest.php
- tests/Unit/Helper/HTMLParser/HttpMicrodataParserTest.php
- tests/Unit/Service/RecipeExtractionServiceTest.php
Closes #217 
This is the last part to finish the structure in order to make domain-antagonistic parsers possible.
> Pass the url to the parsers of the recipes to allow for domain-specific parsers

- CHANGELOG.md
- src/components/AppControls.vue
- src/components/AppNavi.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView.vue
- src/components/SearchResults.vue
- src/js/helper.js
- src/main.js
This is just a small refractory to have the entry point file and the `window` global variable less cluttered.
> Clean up entry file and move helper functions to its own module

- CHANGELOG.md
- src/components/RecipeIngredient.vue
- src/components/RecipeInstruction.vue
- src/components/RecipeTool.vue
- src/components/RecipeView.vue
- src/guest.js
- src/js/api-interface.js
- src/js/title-rename.js
- src/main.js
Closes #935
This is a pure frontend development and is not done very efficiently. There is no caching involved and the same recipe might be requested multiple times.
> Add names of recipes to internal references

- .php-cs-fixer.dist.php
- CHANGELOG.md
- cookbook.code-workspace
- lib/Db/DbTypesPolyfillHelper.php
- lib/Db/RecipeDb.php
- lib/Helper/Filter/AbstractRecipeFilter.php
- lib/Helper/Filter/DB/RecipeDatesFilter.php
- lib/Helper/Filter/NormalizeRecipeFileFilter.php
- lib/Migration/Version000000Date20220703174647.php
- lib/Search/Provider.php
- lib/Service/DbCacheService.php
- lib/Service/RecipeService.php
- tests/Migration/Setup/Migrations/Version000000Date20220703174647Test.php
- tests/Unit/Helper/Filter/DB/RecipeDatesFilterTest.php
- tests/Unit/Helper/Filter/NormalizeRecipeFileFilterTest.php
> Add the creation and modification date as column in the database

- .github/actions/run-tests/tests/entrypoints/test.sh
- .github/workflows/tests.yml
- CHANGELOG.md
- composer.json
- composer.lock
- lib/Controller/RecipeController.php
- lib/Db/RecipeDb.php
- lib/Helper/HtmlToDomParser.php
- lib/Helper/ImageService/ImageFileHelper.php
- lib/Helper/ImageService/ThumbnailFileHelper.php
- lib/Migration/Version000000Date20210701093123.php
- lib/Search/Provider.php
- lib/Service/ImageService.php
- lib/Service/RecipeService.php
- tests/Migration/Setup/Migrations/Version000000Date20210701093123Test.php
- tests/Unit/Controller/RecipeControllerTest.php
- tests/Unit/Helper/UserConfigHelperTest.php
- tests/Unit/Service/ThumbnailServiceTest.php
This should make the dependencies more stable
> Add composer lock file to git and fix code styling

- lib/Controller/MainController.php
- package-lock.json
- package.json
- src/guest.js
- src/main.js
The old name causes problems when using the webpack `file-loader`. The
URL from this would start `/apps/nextcloud-cookbook` although the proper
install location and the proper URL to load the file is
`/apps/cookbook`.
Besides this `file-loader` issue, this change makes everything more
consistent and more conformal to best practices.
I am assuming that URLs like the GitHub repository and matrix should remain the same.
> Rename the app from nextcloud-cookbook to cookbook

- CHANGELOG.md
- src/components/RecipeListKeywordCloud.vue
Fixes #1100 
If there are no keywords, I just don't show the ordering buttons. I also updated the styles using flexbox to layout the buttons a bit better (IMO). Before, the buttons were slightly under the keywords. Now, they are top-aligned.
Before:
After:
> Fix keyword ordering buttons clipped by top bar

- CHANGELOG.md
- lib/Helper/Filter/JSON/FixRecipeYieldFilter.php
- src/components/EditInputField.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView.vue
- tests/Unit/Helper/Filter/JSON/FixRecipeYieldFilterTest.php
> Make recipeYield optional

- CHANGELOG.md
- src/components/AppControls.vue
- src/components/AppControls/AppControls.vue
- src/components/AppControls/Location.vue
- src/components/AppControls/ModeIndicator.vue
- src/components/AppMain.vue
- src/components/AppNavi.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView.vue
- Remove the troublesome `Breadcrumbs` component.
- Show the "location" (recipe name, category name, etc) in an `h2`. Consistently show the "mode" where applicable (Viewing category, Viewing recipe, Editing recipe). Previously, "Edit" was shown when editing, but nothing was shown when viewing. This should be more clear and consistent.
- Move all of the buttons to the right of the bar. Each page should have a primary button (Edit, Save, Search) and all the rest go into an overflow 3-dot menu
To-do:
Fixes #281
Fixes #896 
https://user-images.githubusercontent.com/8503756/180622714-5f3f1c98-fedb-40f9-b7e1-a0c733f273e5.mp4
> Remove Breadcrumbs component

- CHANGELOG.md
- src/guest.js
- src/main.js
> Cleaned out entry scripts

- CHANGELOG.md
- src/components/RecipeEdit.vue
Fixes #1073
`this.recipe_id` is null, so use the recipe ID saved in the store.
I've tested it in the browsed. Where I was seeing `POST` before, I am now seeing `PUT`.
> Fix the endpoint used for updating recipes

- .github/workflows/dependabot-approve-merge.yml
- CHANGELOG.md
Automated update of the dependabot-approve-merge.yml workflow from https://github.com/nextcloud/.github
> Updating dependabot-approve-merge.yml workflow from template

- .github/actions/run-tests/test_runner/runner.py
- CHANGELOG.md
- lib/Helper/Filter/JSON/FixIngredientsFilter.php
- lib/Helper/Filter/JSON/FixInstructionsFilter.php
- lib/Helper/Filter/JSON/FixToolsFilter.php
- tests/Integration/Helper/Filter/JSON/FixIngredientsFilterTest.php
- tests/Integration/Helper/Filter/JSON/FixInstructionsFilterTest.php
- tests/Integration/Helper/Filter/JSON/FixToolsFilterTest.php
- tests/Unit/Helper/Filter/JSON/FixIngredientsFilterTest.php
- tests/Unit/Helper/Filter/JSON/FixInstructionsFilterTest.php
This fixes a regression introduced in #1097. It was not possible to type multi-line text in instructions, ingredients, and tools fields.
> Fix filters to allow for multi-line text in some fields

- .github/actions/run-tests/tests/entrypoints/default-entrypoint.sh
- CHANGELOG.md
- lib/Helper/Filter/JSON/FixInstructionsFilter.php
- tests/Unit/Helper/Filter/JSON/FixInstructionsFilterTest.php
> Accept HowToSteps in recipe instructions

- .github/actions/run-tests/action.yml
- .github/actions/run-tests/test_runner/coverate_rotation.py
- .github/actions/run-tests/test_runner/runner.py
- .github/workflows/tests.yml
- CHANGELOG.md
> Fix code coverage reporting

- CHANGELOG.md
- appinfo/routes.php
- docs/dev/api/changelog/0.md
This finished the migration of the api endpoints. All deprecated API endpoints are finally removed.
> Removed api routes as announced

- CHANGELOG.md
- src/js/api-interface.js
The API access methods had some styling drawbacks.
Also, all requests are forced to `application/json` via header now to be consistent with OpenAPI definition.
> Fix some styling issues in the API access methods

- .github/actions/run-tests/test_runner/docker_management.py
- CHANGELOG.md
This will create and use the docker images for MySQL and PostgreSQL with eatmydata enabled. This should speed up the CI tests a bit.
> Create docker images for databases

- CHANGELOG.md
- lib/Helper/HTMLParser/HttpMicrodataParser.php
- tests/Unit/Helper/HTMLParser/HttpMicrodataParserTest.php
- tests/Unit/Helper/HTMLParser/res_Microdata/caseFix1209.html
- tests/Unit/Helper/HTMLParser/res_Microdata/caseFix1209.json
- tests/Unit/Helper/HTMLParser/res_Microdata/caseFix1209.url
> Fix XPath in microdata parser

- CHANGELOG.md
- lib/Helper/Filter/JSON/FixIngredientsFilter.php
- lib/Helper/Filter/JSON/FixInstructionsFilter.php
- lib/Helper/Filter/JSON/FixToolsFilter.php
- tests/Integration/Helper/Filter/JSON/FixToolsFilterTest.php
- tests/Unit/Helper/Filter/JSON/FixIngredientsFilterTest.php
- tests/Unit/Helper/Filter/JSON/FixInstructionsFilterTest.php
- tests/Unit/Helper/Filter/JSON/FixToolsFilterTest.php
> Fix/1210 recipe filtering resulting in non-contiguous arrays

- .github/workflows/pages.yml
- CHANGELOG.md
- docs/Makefile
The build process for the GitHub pages should contain an action to check for plantuml files and compile them in a prestep. This should allow simpler documentation generation.
> Prepare uml diagram generation during Jekyll build

- CHANGELOG.md
- docs/dev/contributing/setup.md
I wanted to setup my development environment on a different computer, and reading this section, it seemed that the `docker-compose.yml` by christianlupus was in this repository.
> Link to nextcloud-docker-dev and nextcloud-docker-debug in developer docs

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/AppControls/AppControls.vue
- src/components/AppMain.vue
- src/components/AppNavi.vue
- src/components/AppSettings.vue
- src/components/RecipeEdit.vue
- src/components/RecipeTimer.vue
- src/components/RecipeView.vue
- src/components/SearchResults.vue
- src/components/SimpleAlertModal.vue
- src/components/SimpleConfirmModal.vue
- src/js/helper.js
- src/js/modals.js
- src/main.js
Fixes #842
Add two modals to replace `alert()` and `confirm()` in our code.
> Add vue dialog to replace alert and confirm

- .github/workflows/pull-checks.yml
- CHANGELOG.md
- docs/dev/frontend/webpack-bundle-analyzer.md
- package.json
- webpack.devel.js
The bundle analyzer plugin is very slow. When I am running with `npm run dev`, this plugin takes a few seconds after each compile. This really slows down the code-test loop for no reason (I think 99% of the time, we are fixing bugs and adding new features, not optimizing the bundle). Therefore, this PR disables this plugin by default, and adds another npm script to build with this plugin enabled.
I also fixed `npm run build-dev` using `webpack.config.js` instead of `webpack.devel.js`, which I think was a mistake.
In summary:
- `npm run build` is unchanged
- `npm run build-dev` now uses `webpack.devel.js` and the bundle analyzer plugin is **disabled**
- `npm run build-bundle-analyzer` is a new script that uses `webpack.devel.js` and the bundle analyzer plugin is **enabled**
- `npm run dev` …
> Disable webpack bundle analyzer plugin by default to speed up development cycle

- CHANGELOG.md
- src/js/api-interface.js
This was requested in #1257
This basically adds an [interceptor](https://www.npmjs.com/package/axios#user-content-interceptors) to axios that logs every network request, which could be useful for debugging. It also checks the content-type of each request, and warns if it's not `application/json` or `text/json`.
> Add debug logging on every network request

- CHANGELOG.md
- src/components/AppMain.vue
> Fix printing CSS styles

- CHANGELOG.md
- package.json
- src/components/AppMain.vue
- src/components/AppNavi.vue
- src/components/SettingsDialog.vue
Fixes #1067
Move the AppNavigationSettings from the sidebar to a AppSettingsDialog modal that covers the screen.
This is what it should look like:
This makes it easy for us to add more configuration options for things like notifications and alarms without cluttering the sidebar.
> Create an app configuration

- CHANGELOG.md
- docs/dev/api/0.1.0/objects.yaml
- docs/dev/api/changelog/0.md
For further information please read #1421
> Rework api documentation for better code generation

- .github/actions/deploy/appinfo/info.xml.dist
- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- src/components/AppNavi.vue
The import did no longer work. This was caused by handling of native events in the Vue app. The underlying library was updated and the event indices were wrong. Thus, it should be completely handled by Vue events.
Further, the build environment needed an update as it was missing a dependency.
> Fix of the build environment and the import Vue component

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/AppNavi.vue
Backport of #1442.
This disables the Vue event handling but does not mention this in the changelog as no functional change was introduced.
> Fix build environemnt

- CHANGELOG.md
- docs/dev/misc/automated-testing/index.md
The current documentation for backend testing are very detailed, but not very good for newcomers. This PR adds a quick start guide to help newcomers quickly get started with the defaults. The detailed docs are still there if the developer wants to learn more or use more advanced settings.
> Add quick start guide for backend testing

- CHANGELOG.md
- docs/dev/api/0.1.0/objects.yaml
- docs/dev/api/0.1.0/openapi-cookbook.yaml
- docs/dev/api/changelog/0.md
This is part of #1461. It just contains some minor fixes that does not involve code or behavior updates.
> Fix some OpenAPI typos

- .github/actions/deploy/appinfo/info.xml.dist
- CHANGELOG.md
- appinfo/info.xml
- lib/Controller/Implementation/ConfigImplementation.php
- lib/Helper/UserConfigHelper.php
- lib/Service/RecipeService.php
- src/components/RecipeView.vue
- src/components/SettingsDialog.vue
- src/js/api-interface.js
- src/store/index.js
- tests/Unit/Controller/Implementation/ConfigImplementationTest.php
> Make info block visibility configurable

- CHANGELOG.md
- src/js/api-interface.js
Fixes #1185 
Related to #1283 
Adds logging for network responses as well as network requests. With this, all the features requested in #1185 are implemented.
> Add network logging for responses, not only requests

- CHANGELOG.md
- docs/dev/api/0.1.0/objects.yaml
- docs/dev/api/0.1.1/objects.yaml
- docs/dev/api/0.1.1/openapi-cookbook.yaml
- docs/dev/api/changelog/0.md
implements #1421 and superseds #1445
this covers all Problems I faced when trying to implement a generated API.
---
If anyone else uses code generation and faces Issues with the now renamed objects (Category, Keyword or Url) many languages (if not all) support `typedef`s so you could use something simple like:
```dart
typedef MyOldBadlyNamedClass = TheGreatNewNamedClass;
```
although I think a simple `crtl+f` will do the Trick :)
The api itself does not cahnge jsut it's documentation does. So there isn't any need to update your client in the first place
---
The commits are very self explanatory but feel free to ask anything you don't understand.
> Api rework

- CHANGELOG.md
- lib/Helper/Filter/JSON/RecipeIdTypeFilter.php
- lib/Helper/Filter/JSONFilter.php
- tests/Unit/Helper/Filter/JSON/RecipeIdTypeFilterTest.php
- tests/Unit/Helper/Filter/JSONFilterTest.php
Fixes #1464 
Signed-off-by: Nikolas Rimikis <rimikis.nikolas@gmail.com>
> make server api compliant fixes #1464

- CHANGELOG.md
- src/components/SettingsDialog.vue
Replacing "Couldn't" with "Could not"
> Typo fix, also to prevent escaping issues

- CHANGELOG.md
- README.md
- docs/dev/contributing/index.md
- translationfiles/README.md
> Adapt domain move of Transifex

- CHANGELOG.md
- src/components/RecipeIngredient.vue
- src/components/RecipeView.vue
This pull request adds a client-side yield calculator to the recipe detail page of every recipe and fixes #116 
@christianlupus I wasn't able to find "how to add translations" in the docu. It's my first contribution to a Nextcloud project and I only found a link to transifex. Can you assist/guide me here please?
The function (without translation) is ready:
Screenshots of the mobile version:
> Add yield calculator

- CHANGELOG.md
- package.json
This just allowws live reloading with the current setup in combination with Julius Haertls docker dev environment
> Enable webpack server in development machine from all IPs

- CHANGELOG.md
- src/components/AppMain.vue
For error in console of browser about no defined function `isSmaeBaseRoute`.
No problems with normal functionality
> Fix bug in JS console

- .github/workflows/build-test-images.yml
- .github/workflows/tests.yml
This just fixes the need for up to date images during CI/CD building
> Fix PHP versions in Docker pre-built images

- CHANGELOG.md
- docs/dev/api/0.1.0/objects.yaml
- docs/dev/api/0.1.1/objects.yaml
This reverts commit 07954bf2faffa5cd8bb54898a807680c06b532db.
The `@type` annotation should be still part of the OpenAPI description. Although the returned JSON objects are considered compatible with the schema.org standard, this does not mean, we should not make the implications explicit. Also, this makes reading more clean and avoid misunderstandings regarding if the `@type` is to be present or not.
Just documentation, no effects
> Revert "Removed obsolete parameters from OpenAPI specs"

- .github/workflows/build-test-images.yml
- .github/workflows/deploy-appstore.yml
- .github/workflows/pages.yml
- .github/workflows/publish-test-results.yml
- .github/workflows/pull-checks.yml
- .github/workflows/tests.yml
This PR should prevent usage of the self-hosted runners provided by the NC company. These are rather restricted in terms of storage and the tests tend to fail.
> Prevent self-hosted runners by NC company due to quota issues

- CHANGELOG.md
- src/components/RecipeView.vue
- src/js/helper.js
- src/js/yieldCalculator.js
Fixes at least partially #1603
See it live:
[Screencast from 11.06.2023 23:44:37.webm](https://github.com/nextcloud/cookbook/assets/36242595/c99b2463-cde2-406c-80b4-3b98ea8221aa)
None
> Enhance recipe recalculation algorithm

- CHANGELOG.md
- src/components/SettingsDialog.vue
- src/js/api-interface.js
- src/js/logging.js
This is a quick fix for #1753.
This just cures the symptoms to avoid user disturbance. It should be fixed also on lower levels (#1752).
> Workaround for issue with axios

- CHANGELOG.md
- README.md
I added my Android client to the README.
No concerns.
> Add Android client

- CHANGELOG.md
- package-lock.json
- package.json
This is mainly a reversal of 2f20aee. The change was introduced to allow updating prettier to version 3. With the fix in the upstream library, this temporary workaround can be dropped.
None known.
> Revert versioning scheme of dependency to use normal releases again

- .editorconfig
- CHANGELOG.md
When contributing to the Cookbook app, everyone has different editor settings might may conflict with the project's conventions.
For example, I use spaces over tabs so when I hit the tab key, it inserts necessary number of spaces instead.
This just copies over the `.editorconfig` from [nextcloud/server](https://github.com/nextcloud/server/blob/master/.editorconfig) so that contributors have a more seamless experience when working with the project. As the file defines that the project uses tabs, editors will know to leave tabs as-is.
I removed redundant rules, like `*.feature` and `build/psalm-baseline.xml` which aren't relevant to this repository.
N/A
> chore: add .editorconfig file

- .github/actions/run-tests/run-locally.py
- .github/actions/run-tests/test_runner/argument_parser.py
- .github/actions/run-tests/test_runner/db.py
- .github/actions/run-tests/test_runner/docker_helper.py
- .github/actions/run-tests/test_runner/docker_management.py
- .github/actions/run-tests/test_runner/runner.py
- .github/actions/run-tests/test_runner/test_env.py
- CHANGELOG.md
- docs/dev/contributing/setup.md
Upgrades instructions and the local test runner to use Docker Compose v2 instead of Docker Compose.
Docker Compose v2 has been out for some time, and Docker Compose v1 (`docker-compose`) no longer receives updates.
> From July 2023 Compose V1 stopped receiving updates. It’s also no longer available in new releases of Docker Desktop.
> 
> — https://docs.docker.com/compose/ 
I think it makes sense to push the documentation and commands over to the v2 equivalents now, since this is what most engineers should have installed now. 
I have only tested this locally. I'm not sure if this will work as-is on CI or if more needs to be done.
It's also worth considering if a significant portion of maintainers/contributors cannot upgrade to Docker Compose v2 for some reason? :thinking: (I can't think of …
> chore: upgrade docs to docker compose v2

- .github/workflows/build-appstore.yml
- .github/workflows/deploy-appstore.yml
- CHANGELOG.md
- docs/dev/deployment.md
This PR should make publishing releases possible again.
> Reimplement the basic appstore publishing procedure

- CHANGELOG.md
- docs/dev/api/0.1.1/internal-cookbook.yaml
- docs/dev/api/0.1.1/openapi-cookbook.yaml
- docs/dev/api/0.1.2/index.html
- docs/dev/api/0.1.2/internal-cookbook.yaml
- docs/dev/api/0.1.2/internal.html
- docs/dev/api/0.1.2/objects.yaml
- docs/dev/api/0.1.2/openapi-cookbook.yaml
- docs/dev/api/0.1.2/swagger-initializer-internal.js
- docs/dev/api/0.1.2/swagger-initializer.js
- docs/dev/api/changelog/0.md
- docs/dev/api/index.md
- lib/Helper/Filter/JSON/RecipeIdCopyFilter.php
- lib/Helper/Filter/RecipeStubFilter.php
- tests/Integration/Helper/Filter/JSON/RecipeFixIdsTest.php
- tests/Unit/Helper/Filter/JSON/RecipeIdTypeFilterTest.php
> Make the different API endpoints for Recipe and RecipeStub more consistent

- CHANGELOG.md
- lib/Search/Provider.php
This is a maintenance to remove an old polyfill code for NC20.
None
> Dropped old polyfill code

- CHANGELOG.md
- src/components/RecipeView.vue
Closes #1823
This is just a minor UI issue fixed.
None
> Hide copy button if array is empty

- CHANGELOG.md
- src/components/AppNavi.vue
The `title` prop of the `NcAppNavigationItem` is deprecated and should be replaced by the `name` prop. This PR will do so.
None known.
> Switch to non-deprecated props

- CHANGELOG.md
- src/components/RecipeView.vue
- src/components/SettingsDialog.vue
- src/guest.js
- src/main.js
This is a first step to prevent regular updating of the config on each page reload.
Closes #1752 
The PR just covers the basic changes. The migration to the InitialState is not yet carried out.
> Load config explicitly and remove setup routine of settings component

- CHANGELOG.md
- src/components/RecipeView/RecipeView.vue
Fixes #1937
https://github.com/nextcloud/cookbook/assets/36242595/fa912d42-644f-40e9-b234-b32d3b83e2b7
none.
> fix: wrong parsing of recipe yield input

- .eslintignore
- .github/actions/deploy/appinfo/info.xml.dist
- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- src/components/AppControls/AppControls.vue
- src/components/AppInvalidGuest.vue
- src/components/AppMain.vue
- src/components/AppNavi.vue
- src/components/FormComponents/EditMultiselect.vue
- src/components/FormComponents/EditMultiselectInputGroup.vue
- src/components/List/EmptyList.vue
- src/components/List/RecipeList.vue
- src/components/Modals/SettingsDialog.vue
- src/components/Modals/SimpleAlertModal.vue
- src/components/Modals/SimpleConfirmModal.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView/RecipeView.vue
- src/js/logging.js
- src/store/index.js
Closes #1928
This marks the app as compatible with NC 28.
No tests have been carried out yet.
> Formally make app compatible with NC28

- CHANGELOG.md
- src/components/FormComponents/EditMultiselectInputGroup.vue
> Prevent searching in collapsed nutritient option field

- CHANGELOG.md
- src/components/FormComponents/EditMultiselectInputGroup.vue
> Fix the sorting of nutrition options during editing

- CHANGELOG.md
- src/components/RecipeView/RecipeIngredient.vue
- src/js/yieldCalculator.js
fixes https://github.com/nextcloud/cookbook/issues/1985
https://github.com/nextcloud/cookbook/assets/36242595/1ee962bc-bbb0-4d29-ac88-f787aa8e62a4
none.
> feat: prevent yield calculation for ## as ingredient headline

- .eslintrc.yml
- CHANGELOG.md
- src/components/FormComponents/EditTimeField.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView/RecipeTimer.vue
- src/components/RecipeView/RecipeView.vue
- src/guest.js
- src/main.js
- Update timer display
- Remove `H:MM` from label
- Add units
- Add support for durations with seconds
- Add possibility to define seconds for time periods in recipe editor 
- Make global i18n `n(...)` function available in JS
Closes #1408. Closes #1747 
_This currently only supports translations to left-to-right languages, i.e., first hours, then minutes, then seconds._
> Fix/1408 more consistent UI timer

- CHANGELOG.md
- src/components/RecipeView/RecipeView.vue
- src/js/yieldCalculator.js
https://github.com/nextcloud/cookbook/assets/36242595/de49ddfb-1760-48c9-9e2e-ee52252754ee
none.
> fix: ingredients showing NaN in some cases

- CHANGELOG.md
- src/components/RecipeView/RecipeView.vue
- src/js/yieldCalculator.js
Fixes #1986
Thanks for the video @christianlupus - I haven't knew that I can click "servings" to disable them. When trying to reproduce it I just haven't set it and it was "1" by default.
_Please write, what the PR is about and what it does or should do. This does not need to be very long._
none.
> fix: yield not set calculation error

- CHANGELOG.md
- src/components/AppControls/AppControls.vue
- src/components/AppInvalidGuest.vue
- src/components/AppMain.vue
- src/components/AppNavi.vue
- src/components/FormComponents/EditMultiselect.vue
- src/components/FormComponents/EditMultiselectInputGroup.vue
- src/components/List/EmptyList.vue
- src/components/List/RecipeFilterControlsInline.vue
- src/components/List/RecipeFilterControlsModal.vue
- src/components/List/RecipeList.vue
- src/components/List/RecipeSortSelect.vue
- src/components/Modals/SettingsDialog.vue
- src/components/Modals/SimpleAlertModal.vue
- src/components/Modals/SimpleConfirmModal.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView/RecipeView.vue
This should make eslint happy again if the imports of the @ nextcloud/vue library are carried out as expected.
> Fix import of NC vue components accorindg to intended use

- CHANGELOG.md
- src/components/AppControls/AppControls.vue
- src/components/AppInvalidGuest.vue
- src/components/AppMain.vue
- src/components/AppNavi.vue
- src/components/FormComponents/EditMultiselect.vue
- src/components/FormComponents/EditMultiselectInputGroup.vue
- src/components/List/EmptyList.vue
- src/components/List/RecipeList.vue
- src/components/Modals/SettingsDialog.vue
- src/components/Modals/SimpleAlertModal.vue
- src/components/Modals/SimpleConfirmModal.vue
- src/components/RecipeEdit.vue
- src/components/RecipeView/RecipeView.vue
This is a maintenance backport of https://github.com/nextcloud/cookbook/pull/2250.
> Backport of #2250 manually applied

- CHANGELOG.md
- lib/Controller/Implementation/RecipeImplementation.php
- tests/Unit/Controller/Implementation/RecipeImplementationTest.php
> Fix bug #2269

- CHANGELOG.md
- docs/dev/api/0.1.2/objects.yaml
`int` is not a valid openapi type so automated tools fail parsing the spec 
N.A.
> fix: openapi specification

- CHANGELOG.md
- src/components/List/RecipeFilterControlsInline.vue
- src/components/List/RecipeSortSelect.vue
Currently, there is a error logged in the browser when opening the recipe list:
This PR just sets `labelOutside` to true to quite the warning.
This is just a workaround until the new frontend is in place.
> Add workaround by defining label outside

- CHANGELOG.md
- docs/user/clients/Index.md
The PR removes the client 'nook' from the clients page since it is not longer available. The link to the Play Store does not work and also with a search I could not find it. 
No
> Fix: remove client 'nook' from docs

- .changelog/current/2321-deprecation-warning-in-tests.md
- tests/Unit/Helper/FileSystem/RecipeNameHelperTest.php
The variable expansion in the form of `"${varName}" in PHP is deprecated. Instead, one uses `"{$varName}". The tests have the old syntax and should be fixed.
_None_
> Fix deprecation of variable expansion

- .changelog/current/2323-use-curl-for-downloads.md
- lib/Service/RecipeService.php
> Use CURL for download of images

- .changelog/current/2329-allow-slash-in-recipes.md
- lib/Helper/Filter/JSON/RecipeNameFilter.php
- lib/Helper/TextCleanupHelper.php
- tests/Unit/Helper/Filter/JSON/RecipeNameFilterTest.php
Closes #1463
With a new storage backend this must be revisited. 
> Do no longer cut slashes and backslashes from recipe names

- .changelog/current/2333-time-zone-in-recipe-stubs.md
- lib/Helper/Filter/JSON/TimezoneFixFilter.php
- lib/Helper/Filter/Output/RecipeStubFilter.php
- tests/Unit/Helper/Filter/JSON/TimezoneFixFilterTest.php
Closes #1456
This is mainly a quick fix as the timezone information is not present in the database ATM. Instead, the server time zone is used and assumed stable.
> Use default server time zone if non provided

- .changelog/current/2343-no-dot-at-end-of-file-name.md
- lib/Helper/FileSystem/RecipeNameHelper.php
- tests/Unit/Helper/FileSystem/RecipeNameHelperTest.php
Closes #2332
There could be name clashes if the first 97 chars of two recipes are equal.
> Use underscores to prevent trailing dot in folder names

- .changelog/current/2346-utf-file-names-allow-abbreviation.md
- lib/Helper/FileSystem/RecipeNameHelper.php
- tests/Unit/Helper/FileSystem/RecipeNameHelperTest.php
> Allow for UTF chars in the file name without breaking the backend

- .github/workflows/pull-checks.yml
The current CI implementation does not bail out due to a bug in the `wc -l` usage if no changelog was provided.
None
> Fix bug in CI tests

- .changelog/current/2461-fix-changelog-checker.md
- .github/workflows/pull-checks.yml
Currently, the automerge of the dependabot fails. Dependabot does not create changelog stubs. Although this is generally okay for some files to change without explicit changelog, the generation of the GitHub step summary in the actions tab involves so far a generation of the total Changelog. This fails if there is no matching changelog present.
Should be save to merge, as in the workflow, either the error _no changelog found_ is triggered of the python script is run.
> Skip changelog generation if there is nothing to be viewed

- .changelog/current/2465-allow-auto-updates-changelog-helper.md
- .github/workflows/pull-checks.yml
The python helper schript in `.helpers/changelog` cannot be updated by dependabot. This should fix that.
None
> Enhance the pull checks and allow updates in the changelog helper

- .changelog/current/2396-update-link-to-parser.md
- README.md
I recently wanted to work on the recipe parser to add support for some sites I wanted to import recipes from. When
doing so, I noticed the README.md had a very helpful link to the parser in its FAQ section, so I started by following
that; however, while the link was valid, the method referenced did no longer exist. I ended up backing out of the
file referenced in the link and looking around the nearby files, and quickly found a good place to start working on
the recipe parsing call tree.
In this PReq, I update the answer in that FAQ to point to the place I started, since the place it was referencing
previously was presumably removed in some past refactor.
Minor update to the README
None
There are some formal requirements that should be satisfied. Please mark those by checking the …
> Update link to parser method in README.md

- .changelog/current/2470-uniq-keywords-and-categories.md
- src/composables/useRecipeFilterControls/index.js
This is just the reopend PR #2416 that was killed by a bad push to `master`.
> Reopen of #2416

- .changelog/current/2493-compatibility-nc-30.md
- .github/actions/deploy/appinfo/info.xml.dist
- .github/workflows/tests.yml
- .hook-checkout/.gitignore
- .hooks/pre-push
- appinfo/info.xml
- src/components/RecipeView/RecipeView.vue
This is a preparation to make the upcoming release to let it run with the new server version.
The new server version was not tested much on NC30. Regressions might happen.
> Make the app compatible to NC server 30

- .changelog/current/2421-fix-fraction-ingrediants.md
- src/js/yieldCalculator.js
My solution to #2004. This handles 16ths, else falls back to decimal. I think this is a nice balance between using some fractions, without ending up with stupid denominators.
Will only work if the initial ingredient is given as a fraction. If it's a decimal, or just a whole number, will still remain decimal. Maybe it would make sense to convert everything to fractions where possible, but then maybe not. Perhaps being able to change the behavior in settings would be useful, idk. Also, by design does not do 1/3, 1/5, etc. I don't mind this, in fact I would prefer this way, but I guess in the end it's not up to me.
> Handle fractional ingredients (Fixes #2004)

- .changelog/current/2515-use-firefox-user-agent.md
- lib/Helper/DownloadHelper.php
- lib/Service/HtmlDownloadService.php
This should help to make the import more stable.
We need to check if this solution helps and keep the sent FF version somewhat up to date.
> Add Mozilla Firefox user agent to import script

- .changelog/current/2547-update-client-list.md
- docs/user/clients/Index.md
Adds the correct links to the Cookbook Client in the docs
> fix: links to Cookbook Client

- .changelog/current/2540-allow-mac-automated-builds.md
- .github/actions/run-tests/reset-from-container.sh
- .github/actions/run-tests/test_runner/dumps.py
- .github/actions/run-tests/test_runner/test_env.py
- .github/actions/run-tests/tests/entrypoints/test.sh
This PR fixes #2441. It replaces the `--delete-delay` of rsync by `--delete-before`, because `--delete-delay` isn't implemented in rsync on macOS.
The flag `--delete-before` deletes removed files before copying the changed files. In this scenario the change of this flag shouldn't make any difference.
> fix: replace --delete-delay by --delete-before to work on macos

- .changelog/current/2628-fix-php-issues.md
- composer.json
- composer.lock
- lib/Db/RecipeDb.php
- lib/Helper/Filter/JSON/FixInstructionsFilter.php
- lib/Helper/Filter/JSON/SchemaConformityFilter.php
- lib/Helper/HTMLParser/HttpMicrodataParser.php
- lib/Helper/ImageService/ThumbnailFileHelper.php
- lib/Helper/RestParameterParser.php
- lib/Helper/UserConfigHelper.php
- lib/Service/ImageService.php
- lib/Service/RecipeService.php
- psalm.xml
- tests/psalm-baseline.xml
https://github.com/nextcloud/cookbook/issues/1706
All the issues with JSONResponse will go away when https://github.com/nextcloud/server/pull/50035 is merged and OCP is updated here.
I think after that all remaining issues are related to missing stubs, which I can also make a PR for after this one is merged.
> Fix a lot of psalm issues

- .changelog/current/2661-fix-api-behavior.md
- lib/Controller/Implementation/RecipeImplementation.php
- tests/Unit/Controller/Implementation/RecipeImplementationTest.php
Fixes issue [https://github.com/nextcloud/cookbook/issues/1453](https://github.com/nextcloud/cookbook/issues/1453) and allows the image endpoint to default to returning the full image if no `size` param is specified.
Alternatively the `thumb` size could be used if it's preferred to default to that instead of `full`.
> Fix default recipe image fallback to be a valid value: "full"

- .changelog/current/2828-wakelock.md
- src/components/AppMain.vue
- src/components/FormComponents/EditImageField.vue
- src/components/FormComponents/EditInputGroup.vue
- src/components/FormComponents/EditMultiselect.vue
- src/components/FormComponents/EditMultiselectInputGroup.vue
- src/components/FormComponents/EditTimeField.vue
- src/components/List/RecipeCard.vue
- src/components/List/RecipeFilterControlsModal.vue
- src/components/List/RecipeList.vue
- src/components/Modals/SuggestionsPopup.vue
- src/components/RecipeEdit.vue
- src/components/RecipeKeyword.vue
- src/components/RecipeView/RecipeIngredient.vue
- src/components/RecipeView/RecipeInstruction.vue
- src/components/RecipeView/RecipeNutritionInfoItem.vue
- src/components/RecipeView/RecipeTimer.vue
- src/components/RecipeView/RecipeTool.vue
- src/components/RecipeView/RecipeView.vue
Closes https://github.com/nextcloud/cookbook/issues/2826
While viewing a recipe the screen of the device will no longer lock automatically, making it easier to follow a recipe while cooking in parallel.
None that I can think of.
> feat(RecipeView): Acquire screen wake lock
